[theme]
base = "light"
primaryColor = "#C62828"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#212121"
font = "sans serif"

[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false
